---
- name: Get information on virtual machines running on a Proxmox host
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display information on virtual machines
      community.general.proxmox_kvm:
        api_host: 192.168.20.2
        api_user: root
        api_password: 8cBuZ787
        node: 192.168.20.2
        state: current
        vmid: 100
      register: vm_info

    - name: Display gathered facts
      debug:
        var: vm_info