---
- name: Get information on virtual machines running on a Proxmox host
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: 192.168.20.3
        api_user: root@pam
        api_password: 8cBuZ787
      register: vm_info

    - name: Display gathered facts
      debug:
        var: vm_info