---
- name: Get information on virtual machines running on a Proxmox host
  hosts: proxmox
  gather_facts: yes

  tasks:
    - name: Display information on virtual machines
      community.general.proxmox_kvm:
        api_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        api_user: root@pam
        api_password: "{{ hostvars[inventory_hostname]['ansible_password'] }}"
        node: "{{ hostvars[inventory_hostname]['ansible_node'] }}"
        state: current
        vmid: 100
      register: vm_info

    - name: Display gathered facts
      debug:
        var: vm_info