---
- name: Get information on virtual machines running on a Proxmox host
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display information on virtual machines
      community.general.proxmox_kvm:
        api_host: 192.168.20.2
        api_user: root@pam
        api_password: 8cBuZ787
        node: 192.168.20.2
        state: current
        vmid: 100
      register: vm_info

    - name: Display gathered facts
      debug:
        var: vm_info

    - name: Display CPU, RAM, and storage usage
      debug:
        msg: |
          CPU usage: {{ vm_info.cpu }}%
          RAM usage: {{ vm_info.memory.used / 1024 / 1024 }} MB / {{ vm_info.memory.total / 1024 / 1024 }} MB
          Disk usage: {{ vm_info.disk.used / 1024 / 1024 / 1024 }} GB / {{ vm_info.disk.total / 1024 / 1024 / 1024 }} GB