---
- name: Create Proxmox VM
  hosts: localhost
  gather_facts: no
  
  vars_prompt:
    - name: vm_name
      prompt: "Enter the VM name"

  tasks:

  - name: Create new container automatically selecting the next available vmid.
    community.general.proxmox:
      node: 'tigerhost01'
      api_user: 'root@pam'
      api_password: '8cBuZ787'
      api_host: '192.168.20.2'
      password: '8cBuZ787'
      hostname: 'example.org'
      validate_certs: false
      ostemplate: '/dev/sda3/var/lib/pve/local-btrfs/template/iso/ubuntu-22.04.3-live-server-amd64.iso'