---
- name: Create Proxmox VM
  hosts: localhost
  gather_facts: no
  
  vars_prompt:
    - name: vm_name
      prompt: "Enter the VM name"

  tasks:

  - name: Create new container automatically selecting the next available vmid.
    community.general.proxmox:
      node: 'tigerhost01'
      api_user: 'root@pam'
      api_password: '8cBuZ787'
      api_host: '192.168.20.2'
      password: '8cBuZ787'
      hostname: 'example.org'
      validate_certs: false
      ostemplate: 'local-btrfs:vztmpl/ubuntu-14.04-x86_64.tar.gz'