---
- name: Power on Dell servers via iDRAC
  hosts: dell-idrac
  gather_facts: no
  tasks:
    - name: Power on servers
      dellemc.openmanage.idrac_system_info:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
      delegate_to: localhost