---
- name: Power on Dell servers via iDRAC
  hosts: dell-idrac
  gather_facts: no
  tasks:
    - name: Power off servers
      idrac_server_powerstate:
        hostname: "{{ idrac_ip }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: false
        reset_type: "GracefulShutdown"