---
- name: Power off Dell servers via iDRAC
  hosts: dell-idrac
  gather_facts: no
  tasks:
    - name: Power off servers
      ansible.builtin.include_role:
        name: idrac_server_powerstate
      vars:  
        hostname: "{{ idrac_ip }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: false
        reset_type: "On"